import Image from "next/image";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./../globals.css";
import MainWrapper from "@/components/MainWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <MainWrapper>
        <main className="text-[#131313] lg:px-[8px] md:px-[16px] md:max-w-[700px] py-[70px] pb-[0px] lg:py-0 lg:max-w-[1000px] mx-auto">
          {children}
        </main>
      </MainWrapper>

      <Footer />
    </>
  );
}
